Repository eRentronic/eRentronic-Client, pull requests merged in 2022-11, with the labels that each got.

#65 Purchase page authorization
  src/Pages/Login/index.tsx
  src/apis/api.ts
  src/components/server/Product/Card/index.tsx
  src/components/server/ProductDetail/OrderForm/Decide/Decide.tsx
  src/components/server/ProductDetail/OrderForm/Info/index.tsx
  src/components/server/ProductDetail/OrderForm/index.style.ts
  src/components/server/ProductDetail/OrderForm/index.tsx
  src/components/server/ProductDetail/OrderForm/option/index.tsx
  src/hooks/useAddressApi.tsx
  src/hooks/useMutationPost.ts
  src/templates/SigninForm/index.tsx
Labels: refactor

#60 [refactor] 로그인 페이지
  src/Pages/Login/LoginForm/Actions.ts
  src/Pages/Login/LoginForm/components.tsx
  src/Pages/Login/LoginForm/components/Input.tsx
  src/Pages/Login/LoginForm/components/Logo.tsx
  src/Pages/Login/LoginForm/components/Panel.tsx
  src/Pages/Login/LoginForm/components/UserIdentifyForm.tsx
  src/Pages/Login/LoginForm/components/index.ts
  src/Pages/Login/LoginForm/index.tsx
  src/Pages/Login/SignInForm/components.tsx
  src/Pages/Login/SignInForm/components/AddressForm.tsx
  src/Pages/Login/SignInForm/components/EmailForm.tsx
  src/Pages/Login/SignInForm/components/NameForm.tsx
  src/Pages/Login/SignInForm/components/Panel.tsx
  src/Pages/Login/SignInForm/components/PasswordForm.tsx
  src/Pages/Login/SignInForm/components/SinginInput.tsx
  src/Pages/Login/SignInForm/components/index.ts
  src/Pages/Login/SignInForm/index.tsx
  src/Pages/Login/index.tsx
Labels: refactor

#61 [refactor] 메인 페이지 관련 컴포넌트 및 관심사 리팩터링
  src/Pages/Main/Aside/index.tsx
  src/Pages/Main/Aside/style.tsx
  src/Pages/Main/Contents/index.tsx
  src/Pages/Main/Contents/style.tsx
  src/Pages/Main/index.tsx
  src/Pages/Main/style.tsx
  src/components/server/Product/Card/Card.style.tsx
  src/components/server/Product/Card/Content.style.tsx
  src/components/server/Product/Card/Content.tsx
  src/components/server/Product/Card/Info.style.tsx
  src/components/server/Product/Card/Info.tsx
  src/components/server/Product/Card/Thumbnail.style.tsx
  src/components/server/Product/Card/Thumbnail.tsx
  src/components/server/Product/Card/index.tsx
  src/service/product.ts
  src/utils/utils.ts
Labels: refactor

#66 [refactor] View 컴포넌트 사이드 탭 리팩토링
  .vscode/launch.json
  src/Pages/Login/LoginForm/index.tsx
  src/Pages/Main/Aside/index.tsx
  src/Pages/Main/index.tsx
  src/apis/mainProducts.ts
  src/components/common/Button/style.ts
  src/components/common/Indicator/Spinner.tsx
  src/components/common/Layout/Box.tsx
  src/components/common/Layout/Core.tsx
  src/components/common/Text/Caution/constants.ts
  src/components/common/Text/Caution/index.tsx
  src/components/common/Text/Caution/types.ts
  src/components/common/Text/Navigation/index.tsx
  src/components/common/index.ts
  src/components/server/Filter/SideTab/Category.tsx
  src/components/server/Filter/SideTab/category.style.ts
  src/components/server/Filter/SideTab/category.type.ts
  src/components/server/Filter/SideTab/index.tsx
  src/components/server/Filter/SideTab/reducer.tsx
  src/components/server/ProductDetail/OrderForm/option/index.tsx
  src/hooks/useMutationPost.ts
  src/service/filter.ts
  src/service/login.ts
Labels: refactor

#73 Feat/progress bar
  src/components/common/Indicator/ProgressBar/ProgressBar.stories.tsx
  src/components/common/Indicator/ProgressBar/ProgressBar.tsx
Labels: feat, design

#74 Feat/line
  src/components/common/Line/Line.stories.tsx
  src/components/common/Line/Line.tsx
  src/components/common/Line/index.ts
Labels: feat, design

#76 [feat] View 컴포넌트 Edit/Default image container 구현
  .storybook/preview.js
  src/assets/icons/edit.svg
  src/assets/icons/index.ts
  src/assets/images/defaultImage.png
  src/assets/images/errorImage.png
  src/components/common/Icon/index.tsx
  src/components/common/Icon/types.ts
  src/components/common/Layout/ImageContainer/Default.stories.tsx
  src/components/common/Layout/ImageContainer/Default.tsx
  src/components/common/Layout/ImageContainer/Editable.stories.tsx
  src/components/common/Layout/ImageContainer/Editable.tsx
  src/components/common/Layout/ImageContainer/index.ts
  src/types/svgDeclare.d.ts
Labels: feat, documentation

#75 [feat] modal common component 구현
  src/Pages/Login/SignInForm/components/EmailForm.tsx
  src/Pages/detail/index.tsx
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/index.tsx
  src/components/server/ProductDetail/OrderForm/index.tsx
  src/components/server/ProductDetail/OrderForm/option/index.tsx
  src/recoils/modal/Purchase.ts
  src/recoils/modal/modal.ts
Labels: feat, design

#85 [feat]Pagelist common component 구현
  src/components/common/Modal/Modal.tsx
  src/components/common/PageList/PageList.stories.tsx
  src/components/common/PageList/PageNumber.tsx
  src/components/common/PageList/index.tsx
  src/components/common/PageList/pageList.tsx
  src/components/server/ProductDetail/OrderForm/index.tsx
Labels: feat, design
