Repository eRentronic/eRentronic-Client, pull requests merged in 2022-08, with the labels that each got.

#13 [feat] 정적 검색창 구현
  .eslintrc
  src/Pages/Main.tsx
  src/assets/icons/index.ts
  src/assets/icons/search.svg
  src/components/Filter/SideTab/Category.tsx
  src/components/Filter/SideTab/category.style.ts
  src/components/Filter/SideTab/category.type.ts
  src/components/Header/index.tsx
  src/components/Product/Card/Card.tsx
  src/components/Product/Label/SaleLabel.tsx
  src/components/Search/MainInput.tsx
  src/components/Search/mainInput.style.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/types.ts
  src/components/common/Icon/index.tsx
  src/components/common/Icon/types.ts
Labels: feat, design

#16 [chore] 상태 관리 툴 추가 및 설정
  .eslintrc
  package-lock.json
  package.json
  src/index.tsx
Labels: chore

#18 [feat] 팝업 외부 클릭 시 닫힘 기능 구현
  src/Pages/Main.tsx
  src/components/Header/Popup.tsx
  src/components/Header/index.tsx
  src/components/Header/popUp.types.ts
  src/components/common/Input/index.tsx
  src/recoils/popUp/popUp.ts
Labels: feat

#20 [feat] GOI store 생성
  src/recoils/Products/products.ts
  src/recoils/filter/filter.ts
Labels: feat

#24 Er 67 design footer
  package-lock.json
  src/Pages/Main.tsx
  src/components/Footer/PortFolio.tsx
  src/components/Footer/index.style.ts
  src/components/Footer/index.tsx
  src/components/Footer/index.types.ts
  src/styles/globlaTheme.ts
  src/types/globalTheme.d.ts
Labels: design

#26 Er 64 feat 유저 편의성 패널 구현
  src/Pages/Main.tsx
  src/assets/icons/index.ts
  src/assets/icons/moon.svg
  src/assets/icons/sun.svg
  src/components/panel/index.style.ts
  src/components/panel/index.tsx
  src/recoils/dark/dark.ts
  src/styles/globlaTheme.ts
  src/types/globalTheme.d.ts
Labels: feat

#27 [refactor] 파일, 폴더 구조 컨벤션 재정립 공유
  src/components/client/Footer/PortFolio.tsx
  src/components/client/Footer/index.style.ts
  src/components/client/Footer/index.tsx
  src/components/client/Footer/index.types.ts
  src/components/client/Header/PopUp.tsx
  src/components/client/Header/index.styles.ts
  src/components/client/Header/index.tsx
  src/components/client/Header/popUp.style.ts
  src/components/client/Header/popUp.types.ts
  src/components/client/Panel/index.style.ts
  src/components/client/Panel/index.tsx
  src/components/server/Filter/SideTab/Category.tsx
  src/components/server/Filter/SideTab/category.style.ts
  src/components/server/Filter/SideTab/category.type.ts
  src/components/server/Filter/SideTab/dummy.ts
  src/components/server/Filter/SideTab/index.style.ts
  src/components/server/Filter/SideTab/index.tsx
  src/components/server/Product/Card/Content.tsx
  src/components/server/Product/Card/card.style.ts
  src/components/server/Product/Card/index.tsx
  src/components/server/Product/Label/index.tsx
  src/components/server/Search/index.style.ts
  src/components/server/Search/index.tsx
Labels: refactor
